export const GET_RECORDS = 'GET_RECORDS'
export const GET_RECORDS_LOADING = 'GET_RECORDS_LOADING'
export const GET_RECORDS_SUCCESS = 'GET_RECORDS_SUCCESS'
export const GET_RECORDS_ERROR = 'GET_RECORDS_ERROR'

export const ADD_DETAILS = 'ADD_DETAILS'
export const ADD_DETAILS_LOADING = 'ADD_DETAILS_LOADING'
export const ADD_DETAILS_SUCCESS = 'ADD_DETAILS_SUCCESS'
export const ADD_DETAILS_ERROR = 'ADD_DETAILS_ERROR'

export const DELETE_DETAILS = 'DELETE_DETAILS'
export const DELETE_DETAILS_LOADING = 'DELETE_DETAILS_LOADING'
export const DELETE_DETAILS_SUCCESS = 'DELETE_DETAILS_SUCCESS'
export const DELETE_DETAILS_ERROR = 'DELETE_DETAILS_ERROR'

export const UPDATE_DETAILS = 'UPDATE_DETAILS'
export const UPDATE_DETAILS_LOADING = 'UPDATE_DETAILS_LOADING'
export const UPDATE_DETAILS_SUCCESS = 'UPDATE_DETAILS_SUCCESS'
export const UPDATE_DETAILS_ERROR = 'UPDATE_DETAILS_ERROR'
