export const GET_RECORDS = 'GET_RECORDS'
export const GET_RECORDS_LOADING = 'GET_RECORDS_LOADING'
export const GET_RECORDS_SUCCESS = 'GET_RECORDS_SUCCESS'
export const GET_RECORDS_ERROR = 'GET_RECORDS_ERROR'

export const ADD_RECORDS = 'ADD_RECORDS'
export const ADD_RECORDS_LOADING = 'ADD_RECORDS_LOADING'
export const ADD_RECORDS_SUCCESS = 'ADD_RECORDS_SUCCESS'
export const ADD_RECORDS_ERROR = 'ADD_RECORDS_ERROR'

export const DELETE_RECORDS = 'DELETE_RECORDS'
export const DELETE_RECORDS_LOADING = 'DELETE_RECORDS_LOADING'
export const DELETE_RECORDS_SUCCESS = 'DELETE_RECORDS_SUCCESS'
export const DELETE_RECORDS_ERROR = 'DELETE_RECORDS_ERROR'

export const UPDATE_RECORDS = 'UPDATE_RECORDS'
export const UPDATE_RECORDS_LOADING = 'UPDATE_RECORDS_LOADING'
export const UPDATE_RECORDS_SUCCESS = 'UPDATE_RECORDS_SUCCESS'
export const UPDATE_RECORDS_ERROR = 'UPDATE_RECORDS_ERROR'
